
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";
import ModalContainer from "@/components/partials/containers/ModalContainer";
import TantackQueryProvider from "@/components/partials/providers/TantackQueryProvider";
import { Toaster } from "react-hot-toast";
import { yekanBakh } from "./fonts";
import NetworkProvider from "@/components/partials/providers/NetworkProvider";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="fa" dir="rtl">
      <body
        className={yekanBakh.className}
      >

        <TantackQueryProvider>
          <ModalContainer>
            <Header  />
        <NetworkProvider>
            <main style={{ minHeight: "734px" }}>{children}</main>
        </NetworkProvider>
            <Footer />
          </ModalContainer>
        </TantackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
