import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";
import ModalContainer from "@/components/partials/containers/ModalContainer";
import TantackQueryProvider from "@/components/partials/providers/TantackQueryProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TantackQueryProvider>
          <ModalContainer>
            <Header />
            <main style={{ minHeight: "1000px" }}>{children}</main>
            <Footer />
          </ModalContainer>
        </TantackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
